Language: 'English'
Prefix: '&7[&2AdvancedEconomyPlus&7] &r'
Bungee: false
Mysql:
  Status: false
  Host: '127.0.0.1'
  Port: 3306
  DatabaseName: 'mydatabase'
  SSLEnabled: false
  AutoReconnect: true
  VerifyServerCertificate: false
  User: 'admin'
  Password: 'not_0123456789'
  TableNameI: 'economyPlayerData'
  TableNameII: 'economyBankData'
  TableNameIII: 'economyLogger'
  TableNameIV: 'economyTrend'
  TableNameV: 'economyStandingOrder'
  TableNameVI: 'economyDebtRepayment'

Identifier:
  Click: 'click'
  Hover: 'hover'
Seperator:
  BetweenFunction: '~'
  WhithinFuction: '@'
  Space: '+'
  HoverNewLine: '~!~'
  
StartMoney: 0.0
CurrencyNameSingular: 'Euro'
CurrencyNamePlural: 'Euros'

UsePlayerAccount: true
UseBank: false
UseStandingOrder: false
UseLoan: false

TrendLogger:
  ValueIsStabil: 1000.0
GraficSpaceSymbol: 'Ë‰'
GraficPointSymbol: 'x';
  
JobsRebornHookTaskTimer:
- 0
- 15
- 30
- 45

ReservedNames:
- YourServer

BankAccountFromat: 'FOUR_DIGITS_TIMES_THREE'

StandingOrderRepeatTime: '180' #How Often in seconds the Schedular for StandingOrder should check
LoanRepaymentRepeatTime: '180'