main: main.java.me.avankziar.aep.spigot.AdvancedEconomyPlus
name: AdvancedEconomyPlus
version: 3
load: STARTUP
api-version: 1.16
description: a Economy-Plugin
author: Avankziar
depend: [Vault]
softdepend: [ChestShop,JobsReborn,HeadDatabase,QuickShop]
commands:
  econ:
    description: base admin and info command
  money:
    description: base money Command